version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinelml-api
    command: uvicorn api.app:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinelml-exporter
    command: python monitoring/metrics_exporter.py
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinelml-scheduler
    command: python monitoring/scheduler.py
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: sentinelml-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: sentinelml-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/sentinelml_dashboard.json:/etc/grafana/dashboards/sentinelml_dashboard.json
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
